# Generated by Django 2.1.3 on 2019-12-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=200)),
                ('galochka', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='modelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('click_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('start', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotingAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_votings_app.Voting')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_votings_app.VotingAnswer'),
        ),
    ]
