# Generated by Django 3.0 on 2019-12-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_votings_app', '0002_auto_20191213_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='like_count',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='started',
        ),
        migrations.RemoveField(
            model_name='votinganswer',
            name='votes_count',
        ),
    ]
