# Generated by Django 3.0 on 2019-12-13 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_votings_app', '0003_auto_20191213_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='ends',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 21, 42, 54, 817731, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='voting',
            name='start',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 21, 42, 54, 817702, tzinfo=utc)),
        ),
    ]
