# Generated by Django 3.0 on 2019-12-13 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_votings_app', '0004_auto_20191213_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinganswer',
            name='votes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voting',
            name='ends',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 21, 44, 15, 32946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 21, 44, 15, 32916, tzinfo=utc)),
        ),
    ]
