# Generated by Django 3.0 on 2019-12-13 21:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_votings_app', '0005_auto_20191213_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='ends',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 21, 48, 42, 661084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 21, 48, 42, 661045, tzinfo=utc)),
        ),
    ]
