# Generated by Django 3.0 on 2019-12-13 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_votings_app', '0006_auto_20191213_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='ends',
        ),
        migrations.AlterField(
            model_name='voting',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 21, 52, 48, 892758, tzinfo=utc)),
        ),
    ]
