# Generated by Django 3.0 on 2019-12-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_votings_app', '0007_auto_20191213_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
